name: Build and Push Image


on:
    workflow_dispatch:
      branches:
        - main
      inputs:
        id:
          description: 'run identifier'
          required: false
    push:
      branches:
        - main
env:
    DOCKER_IMAGE_NAME: sheriffexcel/signoz-app

jobs:

    build-and-push-image:
        runs-on: ubuntu-latest

        steps:
            # - name: ${{github.event.inputs.id}}
            #   run: echo run identifier ${{ inputs.id }}
            
            - name: Checkout Codebase
              uses: actions/checkout@v4


            - uses: mr-smithers-excellent/docker-build-push@v6
              name: Build & push Docker image
              with:
                image: ${{ env.DOCKER_IMAGE_NAME }}
                tags: latest
                registry: docker.io
                dockerfile: Dockerfile
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            